<?php
# This file was automatically generated by the MediaWiki 1.44.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# Skip this file during MediaWiki installation
# The installer uses MW_CONFIG_CALLBACK instead of loading LocalSettings.php
if ( defined( 'MEDIAWIKI_INSTALL' ) || defined( 'MW_CONFIG_CALLBACK' ) ) {
	return;
}

# Suppress PHP 8.5 compatibility warnings (NAN coercion, etc.)
# These are harmless warnings from MediaWiki code that works fine
error_reporting( E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_WARNING );
ini_set( 'display_errors', 0 );
ini_set( 'log_errors', 1 );

# Temporarily enable error display for debugging (remove after fixing)
# ini_set( 'display_errors', 1 );
# error_reporting( E_ALL );

# ============================================================================
# Environment Detection and Configuration
# ============================================================================
# Detect if running in production (App Engine) or development
$isProduction = ( getenv( 'MW_ENVIRONMENT' ) === 'production' || 
                  getenv( 'GAE_ENV' ) !== false );

# Helper function to get secret from Secret Manager or environment variable
# Only define if not already defined (for installer compatibility)
if ( !function_exists( 'getSecret' ) ) {
	function getSecret( $secretName, $default = null ) {
		# First try environment variable (may be set from Secret Manager or app.yaml)
		$value = getenv( $secretName );
		if ( $value !== false && $value !== '' ) {
			return $value;
		}
		
		# In production, try to access Secret Manager via REST API
		# Use @ to suppress errors if curl or network fails
		if ( getenv( 'MW_ENVIRONMENT' ) === 'production' || getenv( 'GAE_ENV' ) !== false ) {
			if ( !function_exists( 'curl_init' ) ) {
				# curl not available, fall back to default
				return $default;
			}
			
			try {
				# Get access token from metadata server
				$tokenUrl = 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token';
				$tokenHeaders = [ 'Metadata-Flavor: Google' ];
				
				$ch = @curl_init( $tokenUrl );
				if ( $ch === false ) {
					return $default;
				}
				
				curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
				curl_setopt( $ch, CURLOPT_HTTPHEADER, $tokenHeaders );
				curl_setopt( $ch, CURLOPT_TIMEOUT, 2 );
				curl_setopt( $ch, CURLOPT_CONNECTTIMEOUT, 2 );
				$tokenResponse = @curl_exec( $ch );
				$tokenHttpCode = curl_getinfo( $ch, CURLINFO_HTTP_CODE );
				@curl_close( $ch );
				
				if ( $tokenHttpCode === 200 && $tokenResponse ) {
					$tokenData = @json_decode( $tokenResponse, true );
					if ( $tokenData && isset( $tokenData['access_token'] ) ) {
						$projectId = getenv( 'GOOGLE_CLOUD_PROJECT' ) ?: 'agapedia';
						$secretUrl = "https://secretmanager.googleapis.com/v1/projects/{$projectId}/secrets/{$secretName}/versions/latest:access";
						$secretHeaders = [
							"Authorization: Bearer {$tokenData['access_token']}",
							'Content-Type: application/json'
						];
						
						$ch = @curl_init( $secretUrl );
						if ( $ch !== false ) {
							curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
							curl_setopt( $ch, CURLOPT_HTTPHEADER, $secretHeaders );
							curl_setopt( $ch, CURLOPT_TIMEOUT, 2 );
							curl_setopt( $ch, CURLOPT_CONNECTTIMEOUT, 2 );
							$secretResponse = @curl_exec( $ch );
							$secretHttpCode = curl_getinfo( $ch, CURLINFO_HTTP_CODE );
							@curl_close( $ch );
							
							if ( $secretHttpCode === 200 && $secretResponse ) {
								$secretData = @json_decode( $secretResponse, true );
								if ( $secretData && isset( $secretData['payload']['data'] ) ) {
									return @base64_decode( $secretData['payload']['data'] );
								}
							}
						}
					}
				}
			} catch ( Exception $e ) {
				# Silently fail and use default
			} catch ( Throwable $e ) {
				# Catch any other errors
			}
		}
		
		# Fallback to default
		return $default;
	}
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Aga-pedia";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
if ( $isProduction ) {
	# Use production URL from environment variable or App Engine default
	$wgServer = getenv( 'MW_SERVER_URL' ) ?: 
	            ( 'https://' . getenv( 'GOOGLE_CLOUD_PROJECT' ) . '.appspot.com' );
} else {
	$wgServer = "http://localhost:8080";
}

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
## TODO: Add your logo file to resources/assets/Logo-white-background.png
$logoPath = "$wgResourceBasePath/resources/assets/Logo-white-background.png";
$defaultLogoPath = "$wgResourceBasePath/resources/assets/mediawiki.png";

$wgLogos = [
	'1x' => file_exists( __DIR__ . "/resources/assets/Logo-white-background.png" ) ? $logoPath : $defaultLogoPath,
	'icon' => file_exists( __DIR__ . "/resources/assets/Logo-white-background.png" ) ? $logoPath : $defaultLogoPath,
];

## Favicon configuration
## Set the favicon to use the Camp Agawam logo
$wgFavicon = file_exists( __DIR__ . "/resources/assets/Logo-white-background.png" ) ? $logoPath : $defaultLogoPath;

## Apple Touch Icon (for iOS devices)
$wgAppleTouchIcon = file_exists( __DIR__ . "/resources/assets/Logo-white-background.png" ) ? $logoPath : $defaultLogoPath;

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "postgres";

if ( $isProduction ) {
	# Production: Cloud SQL via Unix socket
	# Cloud SQL connection name format: PROJECT_ID:REGION:INSTANCE_NAME
	# Unix socket path: /cloudsql/PROJECT_ID:REGION:INSTANCE_NAME
	$cloudSqlInstance = getenv( 'CLOUD_SQL_INSTANCE' );
	if ( $cloudSqlInstance ) {
		$wgDBserver = "/cloudsql/{$cloudSqlInstance}";
	} else {
		# Fallback: construct from environment variables
		$projectId = getenv( 'GOOGLE_CLOUD_PROJECT' ) ?: 'agapedia';
		$region = getenv( 'CLOUD_SQL_REGION' ) ?: 'us-central1';
		$instanceName = getenv( 'CLOUD_SQL_INSTANCE_NAME' ) ?: 'agapedia';
		$wgDBserver = "/cloudsql/{$projectId}:{$region}:{$instanceName}";
	}
	
	# Get database credentials from environment variables (set from Secret Manager)
	$wgDBname = getenv( 'DB_NAME' ) ?: getSecret( 'db-name', 'agapedia_wiki' );
	$wgDBuser = getenv( 'DB_USER' ) ?: getSecret( 'db-user', 'postgres' );
	$wgDBpassword = getenv( 'DB_PASSWORD' ) ?: getSecret( 'db-password', '' );
	
	# If password is still empty, this will cause connection failure
	# Log a warning but continue (MediaWiki will show a proper error)
	if ( empty( $wgDBpassword ) ) {
		error_log( 'WARNING: Database password not set. Check Secret Manager secrets: db-password' );
		error_log( 'DEBUG: DB_NAME=' . $wgDBname . ', DB_USER=' . $wgDBuser . ', DB_SERVER=' . $wgDBserver );
		# For debugging: enable error display temporarily
		# ini_set( 'display_errors', 1 );
		# error_reporting( E_ALL );
	}
	
	# Postgres specific settings for production
	$wgDBport = "5432";  # Not used with Unix socket, but set for compatibility
	$wgDBssl = true;  # Enable SSL for Cloud SQL
	$wgDBmwschema = "public";
} else {
	# Development: Local PostgreSQL
	$wgDBserver = getenv( 'DB_HOST' ) ?: "localhost";
	$wgDBname = getenv( 'DB_NAME' ) ?: "agapedia_wiki";
	$wgDBuser = getenv( 'DB_USER' ) ?: "postgres";
	$wgDBpassword = getenv( 'DB_PASSWORD' ) ?: "dragonite1446";
	
	# Postgres specific settings for development
	$wgDBport = getenv( 'DB_PORT' ) ?: "5432";
	$wgDBssl = false;
	$wgDBmwschema = "public";
}

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;

## Allowed file extensions for uploads
## Restricted to image formats only for security
$wgFileExtensions = [
	'png', 'gif', 'jpg', 'jpeg', 'webp',  // Standard image formats
	'svg',  // Scalable Vector Graphics
];

## Maximum upload size (100MB default, can be adjusted)
## Note: PHP upload_max_filesize and post_max_size may also need adjustment
$wgMaxUploadSize = 104857600; // 100MB in bytes
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "c7f23fd9171666e8d6b59dc58991e8b06b955a926241871e7f5d604456d99136";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "016eb55b02dac901";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector-2022";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.

# Enable API for Express app integration
$wgEnableAPI = true;
$wgEnableWriteAPI = true;

# Configure CORS for Express app (adjust origin as needed)
if ( $isProduction ) {
	# Production: Allow requests from production domain
	$productionDomain = parse_url( $wgServer, PHP_URL_HOST );
	$wgCrossSiteAJAXdomains = [
		"https://{$productionDomain}",
		"http://{$productionDomain}",  # Fallback for HTTP
	];
} else {
	# Development: Allow localhost
	$wgCrossSiteAJAXdomains = ['http://localhost:3000'];
}

# User rights configuration
# Admins (sysop group) can block users and delete pages
$wgGroupPermissions['sysop']['block'] = true;
$wgGroupPermissions['sysop']['delete'] = true;
$wgGroupPermissions['sysop']['userrights'] = true;

# Regular users can create and edit pages (default)
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['user']['createpage'] = true;

# Enable VisualEditor extension
wfLoadExtension( 'VisualEditor' );

# VisualEditor configuration
# Make VisualEditor available for all namespaces (main, user, etc.)
$wgVisualEditorAvailableNamespaces = [
	'*' => true,  # Enable for all namespaces
];

# Enable VisualEditor for all users by default
$wgDefaultUserOptions['visualeditor-editor'] = 'visualeditor';

# Load Camp Background extension
wfLoadExtension( 'CampBackground' );

# ============================================================================
# Google Cloud Storage Configuration (Production Only)
# ============================================================================
if ( $isProduction ) {
	# Google Cloud Storage bucket name
	$gcsBucket = getenv( 'GCS_BUCKET_NAME' ) ?: 'your-gcs-bucket-name';
	
	# GCS S3-compatible endpoint credentials
	# These should be stored in Secret Manager
	$gcsAccessKey = getenv( 'GCS_ACCESS_KEY' ) ?: getSecret( 'GCS_ACCESS_KEY', '' );
	$gcsSecretKey = getenv( 'GCS_SECRET_KEY' ) ?: getSecret( 'GCS_SECRET_KEY', '' );
	
	# Configure SwiftFileBackend to use GCS S3-compatible API
	# GCS provides an S3-compatible API endpoint
	$wgFileBackends['gcs-backend'] = [
		'name' => 'gcs-backend',
		'class' => \Wikimedia\FileBackend\SwiftFileBackend::class,
		'lockManager' => 'nullLockManager',
		'swiftAuthUrl' => 'https://storage.googleapis.com',  # GCS S3-compatible endpoint
		'swiftUser' => $gcsAccessKey,
		'swiftKey' => $gcsSecretKey,
		'swiftTempUrlKey' => '',  # Optional: for temporary URLs
		'container' => $gcsBucket,
		'wikiId' => 'agapedia',
		'readUsers' => [],  # Optional: read-only users
		'writeUsers' => [],  # Optional: write users
		'connTimeout' => 10,
		'reqTimeout' => 30,
		'shardViaHashLevels' => [ 2, 2 ],  # Sharding for performance
	];
	
	# Configure local file repository to use GCS backend
	$wgLocalFileRepo = [
		'class' => \MediaWiki\FileRepo\LocalRepo::class,
		'name' => 'local',
		'backend' => 'gcs-backend',
		'scriptDirUrl' => $wgScriptPath,
		'scriptExtension' => $wgScriptExtension,
		'url' => "https://storage.googleapis.com/{$gcsBucket}/agapedia-public",
		'hashLevels' => 2,
		'deletedHashLevels' => 3,
		'thumbScriptUrl' => false,
		'transformVia404' => true,
		'initialCapital' => true,
		'deletedDir' => false,
		'fileMode' => 0644,
		'dirMode' => 0755,
		'thumbDir' => "{$wgUploadDirectory}/thumb",
		'transcodedDir' => "{$wgUploadDirectory}/transcoded",
	];
	
	# Update upload directory and path for GCS
	$wgUploadDirectory = false;  # Not used with GCS backend
	$wgUploadPath = "https://storage.googleapis.com/{$gcsBucket}/agapedia-public";
}

