<?php
# This file was automatically generated by the MediaWiki 1.44.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Aga-pedia";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://34.26.133.163";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/camp-logo.png",
	'icon' => "$wgResourceBasePath/resources/assets/camp-logo.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "postgres";
$wgDBserver = "34.26.101.86";
$wgDBname = "agapedia_wiki";
$wgDBuser = "postgres";
$wgDBpassword = "dragonite1446";

# Postgres specific settings
$wgDBport = "5432";
$wgDBssl = false;
$wgDBmwschema = "public";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## Use file-based localization cache instead of database
$wgLocalisationCacheConf['store'] = 'file';
$wgLocalisationCacheConf['storeDirectory'] = "$IP/cache/l10n";
$wgCacheDirectory = "$IP/cache";

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgMaxUploadSize = 100 * 1024 * 1024; // 100 MB
$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'webp', 'svg' ];
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "c7f23fd9171666e8d6b59dc58991e8b06b955a926241871e7f5d604456d99136";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "016eb55b02dac901";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector-2022";

# Enable responsive design for Vector skin
$wgVectorResponsive = true;

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# Mobile Frontend - Auto-detect mobile devices and serve MinervaNeue
wfLoadExtension( 'MobileFrontend' );
$wgMFAutodetectMobileView = true;  # Automatically detect mobile devices
$wgMFDefaultSkinClass = 'SkinMinerva';  # Use Minerva for mobile
$wgMFMobileHeader = 'X-Subdomain';

# MinervaNeue mobile-friendly configuration
$wgMinervaEnableSiteNotice = true;
$wgMinervaAlwaysShowLanguageButton = false;
$wgMinervaShowCategories = [
    'base' => true,
    'beta' => true,
];
$wgMinervaNightModeOptions = [
    'enabled' => true,
    'automatic' => true,
];

# Mobile settings
$wgMFDisplayWikibaseDescriptions = [
    'search' => true,
    'nearby' => true,
    'watchlist' => true,
    'tagline' => true,
];
$wgMFEnableBeta = true;  # Enable beta features for mobile


# End of automatically generated settings.
# Add more configuration options below.

## VisualEditor Extension
wfLoadExtension( 'VisualEditor' );

## DynamicPageList3 - Create dynamic lists of pages
wfLoadExtension( 'DynamicPageList3' );

## Scribunto - Lua scripting (PostgreSQL-compatible)
wfLoadExtension( 'Scribunto' );
$wgScribuntoDefaultEngine = 'luastandalone';

## ParserFunctions - Template logic
wfLoadExtension( 'ParserFunctions' );
$wgPFEnableStringFunctions = true;

# Enable Parsoid REST API (required for VisualEditor in MediaWiki 1.44+)
$wgParsoidEnableREST = true;

# Enable VisualEditor for all namespaces
$wgVisualEditorAvailableNamespaces = [
	NS_MAIN => true,        # Main namespace (articles)
	NS_USER => true,        # User pages
	NS_FILE => true,        # File pages
	NS_CATEGORY => true,    # Category pages
	NS_TEMPLATE => true,    # Template pages
	NS_HELP => true,        # Help pages
];

# Enable VisualEditor for wikitext content model
$wgVisualEditorAvailableContentModels = [
	'wikitext' => 'article',
];

# Allow VisualEditor to work with anonymous users
$wgVisualEditorDisableForAnons = false;

# Debugging (remove after deployment is working)
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
$wgDebugToolbar = false;
$wgDebugDumpSql = true;
$wgDebugLogFile = "/var/www/html/wiki/cache/debug.log";
